#
# .swiftlint.yml
# PoseGallery
#
# Copyright © 2016 Trollwerks Inc. All rights reserved.
#

# references:
# https://github.com/realm/SwiftLint#configuration
#
# swiftlint rules last updated version 0.10.0

disabled_rules:
 - line_length
 - todo

opt_in_rules:
 - empty_count
 - force_unwrapping
 - missing_docs

included:
 - PoseGallery/PoseGallery
 - PoseGallery/PoseGalleryTests
 - PoseGallery/PoseGalleryUITests

excluded:
 - PoseGallery/PoseGallery/resources
 - PoseGallery/PoseGallery/libraries
