#
# .travis.yml
# PoseGallery
#
# Copyright © 2016 Trollwerks Inc. All rights reserved.
#

# references:
# http://www.objc.io/issue-6/travis-ci.html
# http://docs.travis-ci.com/user/build-configuration/
# http://docs.travis-ci.com/user/languages/objective-c/
# https://github.com/kattrali/xcpretty-travis-formatter

# https://github.com/venmo/slather/issues/39 -- track Swift support status
# * https://github.com/venmo/slather#usage

language: objective-c
osx_image: xcode7.3
xcode_sdk: iphonesimulator9.3
xcode_project: PoseGallery.xcodeproj
# xcode_workspace: <WORKSPACE_PLACEHOLDER>
xcode_scheme: PoseGallery

# enable for unsupported toolchains, like pre-release Xcode versions
#branches:
#  except:
#    - feature/Xcode_(UNSUPPORTED_VERSION)

before_install:
 - brew update
 - brew outdated carthage || brew upgrade carthage
# - brew install swiftlint
 - gem install xcpretty --no-rdoc --no-ri --no-document --quiet
 - gem install xcpretty-travis-formatter --no-rdoc --no-ri --no-document --quiet
# - gem install slather --no-rdoc --no-ri --no-document --quiet

install:
- cd PoseGallery
# times out! https://github.com/Carthage/Carthage/issues/1163
# https://github.com/dcaunt/braintree-carthage-test/blob/master/.travis.yml
#- carthage bootstrap --platform iOS --no-use-binaries --verbose
- carthage bootstrap --platform iOS --no-use-binaries

#before_script:

script:
# - swiftlint
#- carthage build --no-skip-current --platform iOS
 - set -o pipefail && xcodebuild clean test -project PoseGallery.xcodeproj -scheme PoseGallery -sdk iphonesimulator CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES | xcpretty -f `xcpretty-travis-formatter`

#after_success:
# - slather

#env:
#global:
# Coveralls API Key
#- secure: XjmvN8ABJy1...
# Github Read-only API Key (for Carthage)
#- secure: h+aeQzBtH+...
# Signing Certificate
#- secure: cX/QpfuEH2wk...