# references:
# http://www.objc.io/issue-6/travis-ci.html
# http://docs.travis-ci.com/user/build-configuration/
# http://docs.travis-ci.com/user/languages/objective-c/
# https://github.com/kattrali/xcpretty-travis-formatter
# https://github.com/SlatherOrg/slather

language: objective-c
osx_image: xcode9.2
xcode_sdk: iphonesimulator11.2
xcode_project: PoseGallery.xcodeproj
xcode_scheme: PoseGallery

branches:
  except:
    - feature/xcode-93

cache:
  directories:
    - Carthage

before_install:
 - brew update && brew bundle
 - bundle install

install:
 - cd PoseGallery
 - carthage bootstrap --verbose --no-use-binaries --platform iOS --cache-builds

before_script:
 - bundle exec danger

script:
 - >
    set -o pipefail && xcodebuild clean test
    -project PoseGallery.xcodeproj
    -scheme PoseGallery
    -sdk iphonesimulator
    -derivedDataPath build
    CODE_SIGN_IDENTITY=""
    CODE_SIGNING_REQUIRED=NO
    CODE_SIGNING_ALLOWED=NO
    ONLY_ACTIVE_ARCH=YES
    GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES
    GCC_GENERATE_TEST_COVERAGE_FILES=YES
    | xcpretty -f `xcpretty-travis-formatter`

after_success:
 - slather
