# references:
# http://www.objc.io/issue-6/travis-ci.html
# http://docs.travis-ci.com/user/build-configuration/
# http://docs.travis-ci.com/user/languages/objective-c/
# http://www.mokacoding.com/blog/xcodebuild-destination-options/
# https://github.com/kattrali/xcpretty-travis-formatter
# https://github.com/SlatherOrg/slather

language: objective-c
osx_image: xcode9.2
xcode_project: PoseGallery.xcodeproj
xcode_scheme: PoseGallery
xcode_sdk: iphonesimulator11.2
gemfile: Gemfile

env:
  global:
    - PROJECT='PoseGallery.xcodeproj'
    - IOS_SCHEME='PoseGallery'
    - IOS_DESTINATION='platform=iOS Simulator,name=iPhone SE'

branches:
  except:
    - feature/xcode-93

cache:
  - bundler
  directories:
    - Carthage

before_install:
 - brew update && brew bundle
 - bundle install

install:
 - carthage bootstrap --no-use-binaries --platform iOS --cache-builds

before_script:
 - bundle exec danger

script:
 - >
    set -o pipefail && travis_retry xcodebuild clean test
    -project "$PROJECT"
    -scheme "$IOS_SCHEME"
    -sdk iphonesimulator
    -destination "$IOS_DESTINATION"
    -derivedDataPath build
    -enableCodeCoverage YES
    CODE_SIGN_IDENTITY=""
    CODE_SIGNING_REQUIRED=NO
    ONLY_ACTIVE_ARCH=YES
    GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES
    GCC_GENERATE_TEST_COVERAGE_FILES=YES
    | xcpretty -f `xcpretty-travis-formatter`

after_success:
  - bundle exec slather
