#
# .travis.yml
# PoseGallery
#
# Copyright (c) 2015 Trollwerks Inc. All rights reserved.
#

# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
before_script:
- gem install xcpretty --no-rdoc --no-ri --no-document --quiet
script:
- set -o pipefail && xcodebuild -project PoseGallery/PoseGallery.xcodeproj -scheme PoseGallery -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty -c
- set -o pipefail && xcodebuild test -project PoseGallery/PoseGallery.xcodeproj -scheme PoseGalleryTests -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty -c