language: objective-c
xcode_project: SwiftyBeaver.xcodeproj
xcode_scheme: SwiftyBeaver (iOS)
osx_image: xcode7.3
xcode_sdk: iphonesimulator9.3
before_install:
- gem install xcpretty
script:
- set -o pipefail  # required to let xcpretty use the same exit code like xcodebuild
- xcodebuild -project SwiftyBeaver.xcodeproj -scheme "SwiftyBeaver (iOS)" -destination name="iPhone 6" -destination name="iPhone 6" test | xcpretty -c
