#
# .travis.yml
# ScreamingParty
#
# Copyright © 2016 Trollwerks Inc. All rights reserved.
#

# references:
# http://www.objc.io/issue-6/travis-ci.html
# http://docs.travis-ci.com/user/build-configuration/
# http://docs.travis-ci.com/user/languages/objective-c/
# https://github.com/kattrali/xcpretty-travis-formatter
# https://github.com/SlatherOrg/slather

language: objective-c
#osx_image: xcode7.3
# https://blog.travis-ci.com/2016-06-13-xcode-8-beta-initial-release
osx_image: xcode8
# http://stackoverflow.com/questions/33747828/a-build-only-device-cannot-be-used-to-run-this-target
#xcode_sdk: iphonesimulator9.3
#xcode_sdk: iphonesimulator10.0
xcode_sdk: iphonesimulator
xcode_project: ScreamingParty.xcodeproj
xcode_scheme: ScreamingParty

# enable for unsupported toolchains, like pre-release Xcode versions
#branches:
#  except:
#    - feature/Xcode_(UNSUPPORTED_VERSION)

before_install:
 - brew update
# - brew outdated carthage || brew upgrade carthage
 - brew install swiftlint
 - gem install slather --no-rdoc --no-ri --no-document --quiet
 - gem install xcpretty --no-rdoc --no-ri --no-document --quiet
 - gem install xcpretty-travis-formatter --no-rdoc --no-ri --no-document --quiet

install:
 - cd ScreamingParty
# - carthage bootstrap --platform iOS --no-use-binaries

#before_script:

script:
 - open -b com.apple.iphonesimulator
# http://www.mokacoding.com/blog/xcodebuild-destination-options/
 - >
    set -o pipefail && xcodebuild clean test
    -project ScreamingParty.xcodeproj
    -scheme ScreamingParty
    -sdk iphonesimulator
    -destination 'platform=iOS Simulator,name=iPhone SE,OS=10.0'
    -derivedDataPath build
    CODE_SIGN_IDENTITY=""
    CODE_SIGNING_REQUIRED=NO
    CODE_SIGNING_ALLOWED=NO
    ONLY_ACTIVE_ARCH=YES
    GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES
    GCC_GENERATE_TEST_COVERAGE_FILES=YES
    | xcpretty -f `xcpretty-travis-formatter`

after_success:
 - swiftlint
 - slather
