// This is a generated file, do not edit!
// Generated by R.swift, see https://github.com/mac-cain13/R.swift

import UIKit

/// :nodoc:struct R {
  /// :nodoc:static func validate() {
    storyboard.main.validateImages()
    storyboard.main.validateViewControllers()
  }
  
  /// :nodoc:struct image {
    /// :nodoc:static var appIcon: UIImage? { return UIImage(named: "AppIcon") }
    /// :nodoc:static var contents: UIImage? { return UIImage(named: "Contents") }
    /// :nodoc:static var first: UIImage? { return UIImage(named: "first") }
    /// :nodoc:static var second: UIImage? { return UIImage(named: "second") }
  }
  
  /// :nodoc:struct nib {
    /// :nodoc:struct launchScreen {
      /// :nodoc:static var instance: UINib { return UINib.init(nibName: "LaunchScreen", bundle: nil) }
      
      /// :nodoc:static func firstView(ownerOrNil: AnyObject?, options optionsOrNil: [NSObject : AnyObject]?) -> UIView? {
        return instantiateWithOwner(ownerOrNil, options: optionsOrNil)[0] as? UIView
      }
      
      /// :nodoc:static func instantiateWithOwner(ownerOrNil: AnyObject?, options optionsOrNil: [NSObject : AnyObject]?) -> [AnyObject] {
        return instance.instantiateWithOwner(ownerOrNil, options: optionsOrNil)
      }
    }
  }
  
  /// :nodoc:struct reuseIdentifier {
    
  }
  
  /// :nodoc:struct segue {
    
  }
  
  /// :nodoc:struct storyboard {
    /// :nodoc:struct main {
      /// :nodoc:static var initialViewController: UITabBarController? { return instance.instantiateInitialViewController() as? UITabBarController }
      /// :nodoc:static var instance: UIStoryboard { return UIStoryboard(name: "Main", bundle: nil) }
      
      /// :nodoc:static func validateImages() {
        assert(UIImage(named: "first") != nil, "[R.swift] Image named 'first' is used in storyboard 'Main', but couldn't be loaded.")
        assert(UIImage(named: "second") != nil, "[R.swift] Image named 'second' is used in storyboard 'Main', but couldn't be loaded.")
      }
      
      /// :nodoc:static func validateViewControllers() {
        
      }
    }
  }
}
