#!/bin/sh

#
# script_build_begin.sh
# PoseGallery
#
# Copyright © 2016 Trollwerks Inc. All rights reserved.
#

# typed resource identifiers

# https://github.com/mac-cain13/R.swift/releases
${SRCROOT}/PoseGallery/libraries/rswift/rswift ${SRCROOT}/PoseGallery/resources
echo R.generated.swift generated by rswift 2.2.2

# icon tagging

if [ $CONFIGURATION != "Release" ] ; then
    ${SRCROOT}/PoseGalleryConfig/script_tag_icon.sh tag PoseGallery/resources/Images.xcassets/AppIcon.appiconset
    echo tag_icon.sh tagged
fi

# undone work warnings

TAGS="TODO:|FIXME:|\?\?\?:|\!\!\!:"
echo "searching ${SRCROOT} for ${TAGS}"
find "${SRCROOT}/PoseGallery" "${SRCROOT}/PoseGalleryTests" "${SRCROOT}/PoseGalleryUITests" \( -name "*.swift" -or -name "*.m" -or -name "*.h" \) -print0 | xargs -0 egrep --with-filename --line-number --only-matching "($TAGS).*\$" | perl -p -e "s/($TAGS)/ warning: \$1/"

# finished

return 0
