#
# .slather.yml
# PoseGallery
#
# Copyright © 2016 Trollwerks Inc. All rights reserved.
#

# references:
# https://github.com/SlatherOrg/slather#usage-with-coveralls

coverage_service: coveralls
xcodeproj: PoseGallery.xcodeproj
scheme: PoseGallery
source_directory: PoseGallery/source
ignore:
 - PoseGalleryConfig/*
 - PoseGalleryTests/*
 - PoseGalleryUITests/*
