#
# .slather.yml
# PoseGallery
#
# Copyright © 2016 Trollwerks Inc. All rights reserved.
#

# https://github.com/SlatherOrg/slather#usage-with-coveralls
coverage_service: coveralls

# https://github.com/SlatherOrg/slather/issues/197
build_directory: build

xcodeproj: PoseGallery.xcodeproj
scheme: PoseGallery

ignore:
 - PoseGalleryConfig/*
 - PoseGalleryTests/*
 - PoseGalleryUITests/*
